'use strict';

const Homey = require('homey');
const path = require('path');

// Load mapping generated by tools/generate-capabilities.js
let mapping = {};
try {
  mapping = require(path.resolve(__dirname, '..', '..', 'data', 'capability-mapping.json'));
} catch (err) {
  // mapping may not exist yet; will be created by generator
  mapping = {};
}

function isPrimitive(v) {
  return (v === null) || ['string','number','boolean'].includes(typeof v);
}

module.exports = class OssResourceDevice extends Homey.Device {
  async onInit() {
    this.log('OssResource device initialized');

    // If we have a previously stored API response, set capabilities from it
    if (this.getStoreValue) {
      try {
        const last = await this.getStoreValue('lastApiResponse');
        if (last) this._setCapabilitiesFromObject(last);
      } catch (e) {
        this.log('Error reading stored lastApiResponse', e.message);
      }
    }

    // Expose a method to update capabilities from an API response; other parts of the app
    // can call device.setCapabilitiesFromApi(response)
    this.setCapabilitiesFromApi = (data) => this._setCapabilitiesFromObject(data);
  }

  // Walk an object recursively and set capability values for any mapped keys
  _setCapabilitiesFromObject(obj) {
    if (!obj || typeof obj !== 'object') return;

    const self = this;

    function applyMapping(key, value) {
      if (value === undefined) return;
      // Prefer full path mapping, fallback to short property name
      let capId = mapping[key];
      if (!capId) {
        const parts = String(key).split('.');
        capId = mapping[parts[parts.length - 1]];
      }
      if (!capId) return;

      // For arrays of primitives, use first element
      if (Array.isArray(value)) {
        if (value.length === 0) return;
        if (isPrimitive(value[0])) value = value[0];
        else value = JSON.stringify(value);
      }

      // Convert boolean-like strings
      if (typeof value === 'string') {
        const v = value.trim().toLowerCase();
        if (v === 'true' || v === 'false') value = (v === 'true');
        else if (!Number.isNaN(Number(value))) value = Number(value);
      }

      // Set capability value (ignore errors)
      try {
        // setCapabilityValue returns a promise; don't await to avoid blocking
        this.setCapabilityValue(capId, value).catch(err => {
          this.log('Error setting capability', capId, err && err.message);
        });
      } catch (err) {
        this.log('Exception setting capability', capId, err && err.message);
      }
    }

    function traverse(node, prefix) {
      if (node === null || node === undefined) return;

      if (isPrimitive(node)) {
        applyMapping(prefix, node);
        return;
      }

      if (Array.isArray(node)) {
        // If array of primitives, try mapping the array at this prefix
        if (node.length > 0 && isPrimitive(node[0])) {
          applyMapping(prefix, node);
          return;
        }
        // Otherwise traverse items using same prefix to match array item mappings
        for (const item of node) traverse(item, prefix);
        return;
      }

      for (const key of Object.keys(node)) {
        const val = node[key];
        const full = prefix ? `${prefix}.${key}` : key;

        if (isPrimitive(val)) {
          applyMapping(full, val);
        } else if (Array.isArray(val)) {
          // array handling: if array of primitives, map the array; else traverse items
          if (val.length > 0 && isPrimitive(val[0])) {
            applyMapping(full, val);
          } else {
            for (const item of val) {
              traverse(item, full);
            }
          }
        } else if (typeof val === 'object') {
          traverse(val, full);
        }
      }
    }

    // Kick off traversal
    traverse(obj, '');

    // Store last API response for potential future inits
    if (this.setStoreValue) {
      try {
        this.setStoreValue('lastApiResponse', obj);
      } catch (e) {
        this.log('Error storing lastApiResponse', e && e.message);
      }
    }
  }
};
